# Generated by Django 3.0.3 on 2020-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='locality',
            field=models.TextField(default='This is cool!'),
        ),
        migrations.AddField(
            model_name='diseases',
            name='virus',
            field=models.CharField(default='This is cool!', max_length=40),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='cause',
            field=models.TextField(default='This is cool!'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='prec',
            field=models.TextField(default='This is cool!'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='symp',
            field=models.TextField(default='This is cool!'),
        ),
    ]
