# Generated by Django 3.0.3 on 2020-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200223_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='cause',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='locality',
            field=models.CharField(default='This is cool!', max_length=40),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='prec',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='symp',
            field=models.TextField(),
        ),
    ]
